### ISSUE TITLE
V 0.0.5 - 2 instances of Presence Footsteps jar in pack.

### ISSUE THREAD

**Issue by TheWyzer** [Chuunkyz/Benchmark-1.17.1#1]
There are 2 jar files for the same mod in the 0.0.5 pack you just released.

Presence Footsteps.jar

**Comment by Chuunkyz** [comment]
ow, i'm gonna release 0.0.6 just now so i'll definitely keep only one of them. thanx for reporting

**Comment by TheWyzer** [comment]
Thank you.
