### ISSUE TITLE
Quest Issues

### ISSUE THREAD

**Issue by TopPercentageRattata** [Chuunkyz/Benchmark-1.17.1#10]
Iron Bundle and others down that quest line cannot be completed because they're smithing table recipes but you have quest set to crafting detection and not just detection.
Adding sodium mod causes storage quest tab quests to all have blank or bugged icons, presumably due to one of the block icons for one of the quests(maybe a cable?). Could potentially fix by changing the quest icons for those quests 1 by 1 until the culprit is found
Backpack quests like iron backpack don't work if you've worn the backpack before since quest is set to only accept freshly crafted iron backpacks and if you've ever worn a backpack in the previous tier before upgrading it has an nbt tag, even if empty it still has an NBT tag different from crafting
Edit: Also, Arcanus spell book quests don't detect the books unless they happen to be written by an EXACT author even though they all can have many possible authors

**Comment by Chuunkyz** [comment]
mmh, thanx for reporting all that stuff
for the sodium texture bugs, i think you forgot indium
i think i'll change a lot of quests to detection in the next update, and i'll also see what i can do with the arcanus books
i don't know if i can ignore nbts so for the backpacks, you'll have to make them empty atm (but i'll still change to detection instead of crafting)

**Comment by TopPercentageRattata** [comment]
Sorry meant Iron Bundle and not satchel for first part
Indium worked, thanks

**Comment by Chuunkyz** [comment]
okay, thanx for the fast reply ^^

**Comment by TopPercentageRattata** [comment]
Deep learner quest doesn't detect Deep learner item since quest looks for a deep learner with NBT but crafting gives an nbt free one

**Comment by Chuunkyz** [comment]
oops, sorry, but everything will probably be nbt free if i can do that in the next version

**Comment by TopPercentageRattata** [comment]
Diamond quiver quest is set to need both silver and gold quiver quests instead of either

**Comment by Chuunkyz** [comment]
thanx for reporting that too, i'm currently fixing the quests :)
