### ISSUE TITLE
heart resetting 

### ISSUE THREAD

**Issue by Irwin5038** [Chuunkyz/Benchmark-1.17.1#12]
when ever I gain health over the normal 20 health it will rest to 20 and it will keep trying to heal those hearts over 20 thus consuming a lot of hunger and just being annoying all round

**Comment by Chuunkyz** [comment]
if you have orange hearts, that means you have more than 20 hp
that's a feature of the health overlay mod, instead of having several bars you'll get different heart colors.
so are you sure that it's not that ?

**Comment by Irwin5038** [comment]
im sorry it was bc of a mod i had added once removed it was fixed
