### ISSUE TITLE
Crash while searching recipes

### ISSUE THREAD

**Issue by Moholmarn** [Chuunkyz/Benchmark-1.17.1#13]
Had the exact result with the previous version, everytime i hit "C" in the searchbox in the inventory, the game crashes. Replicates just fine with and without sodium+iris. Last time the log pointed to that AE was the most likely culprit, this time i see only a reference to mixin. Below is a paste of the latest log, with sodium+iris. If need be i can link to a log without sodium+iris.

https://pastebin.com/53b4DRMa

**Comment by Chuunkyz** [comment]
hey,
you have to use sodium + indium (without shaders) or iris + indium (with shaders)
also, sodium is included in iris, you aren't intended to use both of them together.

**Comment by Moholmarn** [comment]
I'm using iris, but the jar is called "iris+sodium" which is why i called it that. Just downloaded indium, let's se if it crashes again.

Edit: Issue resolved, lack of indium was the problem.
