### ISSUE TITLE
Glowing armor still crashes the client

### ISSUE THREAD

**Issue by Moholmarn** [Chuunkyz/Benchmark-1.17.1#15]
Might be related to issue #9 

https://pastebin.com/T35gsVWJ

**Comment by Chuunkyz** [comment]
that's due to eldritch mobs, and seems like the issue is still not fixed...

**Comment by Moholmarn** [comment]
Saw your ticket on their issue tracker, hopefully they can get it fixed.

**Comment by Chuunkyz** [comment]
fixed in the next update ;)

**Comment by Moholmarn** [comment]
Nice!
