### ISSUE TITLE
crafting conflict between mods

### ISSUE THREAD

**Issue by skeezzzz** [Chuunkyz/Benchmark-1.17.1#16]
When you try to craft a "basic coil" from the iron jetpacks mod, it makes a "red alloy compound" from the RSwires mod. When you look at the red alloy compound recipe it gives you a different combination to make it (which also works). I'm not sure if this is a personal issue I'm having or if this is a universal issue.

**Comment by Chuunkyz** [comment]
oops, thanx for reporting, i fixed that right now
