### ISSUE TITLE
Quest for Knife is broken due to recipe conflict.

### ISSUE THREAD

**Issue by WheresMyMtnDew** [Chuunkyz/Benchmark-1.17.1#17]
Quest: Cooking & Farming - Knife {to unlock the cutting block quest) is no longer craft-able as the recipe is overwritten by knife from Croptopia. This is as of the latest update, version: 1.1.0.

**Comment by Chuunkyz** [comment]
ye, croptopia added a knife, this will be fixed in next update

**Comment by WheresMyMtnDew** [comment]
Thanks!

**Comment by Chuunkyz** [comment]
fixed
