### ISSUE TITLE
Issues with some quests

### ISSUE THREAD

**Issue by Zarvera** [Chuunkyz/Benchmark-1.17.1#18]
Essentia Vessel from Art of Alchemy is not being recognized by the book no matter what for some reason.
Same with Fluid Pipe from Modern Industrialization, and also Life Crystals
Also, Calcination Furnace just destroys Amaranth Pearls and gives nothing (as far as i understand that's how make cracked one, had to google around and translate that part from Japanese wiki - if it's not how you do that, a hint in the quest would be nice, that mod looks like a complete mess)

[upd] Initiate Wand too

**Comment by Chuunkyz** [comment]
fixed
