### ISSUE TITLE
Suggestion:  Add the Gobber Mod

### ISSUE THREAD

**Issue by TheWyzer** [Chuunkyz/Benchmark-1.17.1#2]
As the title suggests, please consider adding the Gobber Mod, I think it adds some interesting items to the game.

https://www.curseforge.com/minecraft/mc-mods/gobber-fabric

**Comment by Chuunkyz** [comment]
i'm totally aware about this mod, but there's 2-3 things i don't like in it, so i really don't know if i should add it or not. i especially hate the mining dimensions.
i also thought of creating my own mod, benchmarkium, to add at least one ore to the modpack (just like allthemodium on forge)
if so the mod will definitely be a bit like gobber with various items related to the new ores, and will fit a lot more into the pack

**Comment by TheWyzer** [comment]
Sounds good.

**Comment by TheWyzer** [comment]
I meant to let you know that under version 1.17+, Gobber removed the Dimensions to a stand alone mod.  Just wanted you to know.
