### ISSUE TITLE
Modpack fails to update

### ISSUE THREAD

**Issue by ItsFlashCraft** [Chuunkyz/Benchmark-1.17.1#20]
curse.radium.installmanagement.installtaskfailedexception
Stops loading mods at workings and gives this error or dependency error 3381267

**Comment by lilrichy** [comment]
I tried downloading fresh and updating version 1.0.1 to 1.1.1 and get the same error but with a different number than the one from @ItsFlashCraft my error is:
Sorry, we can't load this project. Missing dependency: 3343479. Learn more

**Comment by ItsFlashCraft** [comment]
I just tried again and got the same error as you @lilrichy

**Comment by ItsFlashCraft** [comment]
I have found a workaround by using multimc and java 17

**Comment by Trogdayton** [comment]
I managed to get around this issue by using the FTB launcher. But yeah, getting that same 3343479 error on the curseforge app. I tried multiple versions of the pack as well, just in case I could download a previous one and then update. No dice.

**Comment by Chuunkyz** [comment]
MultiMC works too
thats a problem with cf, but will be fixed in next pack update anyway
