### ISSUE TITLE
Suggestion: Plant in a Jar mod

### ISSUE THREAD

**Issue by TheWyzer** [Chuunkyz/Benchmark-1.17.1#3]
First, let me say thanks for this modpack, enjoying it so far, as it's high time to get away from 1.12.  Also sorry I don't know how to add a label, to make this more clear.

To my point.  What do you think about "Plant in a Jar"?   Not sure if you have something else in the pack similar already, I am pretty new to Fabric, enjoying that it is lighter and faster than Forge, but that means I am very unfamiliar with current mods, even more so since 1.17 is still "new".

**Comment by Chuunkyz** [comment]
hello !
I'm glad you're having fun with my pack !
i'm aware of plant in a jar, but i'm finding it a little bit op. an other problem is that it's not compatible with betterend/betternether (at least tast time i tested it)
i'm not sure if i should add it, maybe i'll add it soon, maybe never
i'm considering it for the benchmark skyblock that is in the works, tho

EDIT : also there's machines in indrev that can farm trees iirc

**Comment by TheWyzer** [comment]
Understood.  That is important information, you want a directed pack, and not an actual "kitchen sink", at least that is my understanding/opinion.  I will keep that in mind for any future suggestions.

I did read that the Jar Dev was in talks with the Better End/Nether Dev(s) to resolve the issue, however the Jar Dev does not post much as to what his updates have done/resolved/changed.
