### ISSUE TITLE
Chest quest issue

### ISSUE THREAD

**Issue by Soloist1twitch** [Chuunkyz/Benchmark-1.17.1#5]
The early quest to craft a chest is looking for a minecraft chest.  When you craft a chest, it is the Charm version and does not complete the quest.

**Comment by Chuunkyz** [comment]
i'll try to make the charm chest valid for the quest, but seems like hqm can't do that for the moment
to make a regular chest, you can just put the charm chest in a crafting table and you'll get the regular chest, and you can also use different types of wood. But don't worry, i'll try to fix that.
