### ISSUE TITLE
Suggestion: Add Starlight mod

### ISSUE THREAD

**Issue by OakBricks** [Chuunkyz/Benchmark-1.17.1#6]
the Starlight mod is a mod that optimizes the lighting engine, it is made by the developer of Tuinity and is currently under PaperMC

[link (curse)](https://www.curseforge.com/minecraft/mc-mods/starlight)

**Comment by Chuunkyz** [comment]
hi, i just realized starlight is on curseforge :)
i'll see if it's compatible, and if so i'll definitely add it.
