### ISSUE TITLE
Steel dust requires coal dust and... coal dust.

### ISSUE THREAD

**Issue by TauzentBlitz** [Chuunkyz/Benchmark-1.17.1#7]
The industrial revolution infuser recipe for steel dust is coal dust (tech reborn) and coal dust (industrial revolution).

**Comment by Chuunkyz** [comment]
huh, i don't think this is a problem with my unification, i think this is a 'mistake' in indrev. i'll check with only indrev and i can still fix that myself while waiting the fix in indrev
EDIT : i realized indrev has a new version and i never updated it, maybe this is fixed in this version

**Comment by Chuunkyz** [comment]
seems like all infuser dust recipes are broken, this is really weird
don't worry tho, i'm gonna fix this in the next update
