### ISSUE TITLE
Crash with rendering skeleton with glowing armor

### ISSUE THREAD

**Issue by TopPercentageRattata** [Chuunkyz/Benchmark-1.17.1#9]
[crash-2021-10-10_15.39.40-client.txt](https://github.com/Chuunkyz/Benchmark-1.17.1/files/7318222/crash-2021-10-10_15.39.40-client.txt)
https://paste.ee/p/k7g1E
Not sure what mod adds glowing armor that crashes games so have a crash report, free of charge

**Comment by Chuunkyz** [comment]
fixed in the next update, sorry for not fixing that earlier
